webproject:
    image : lcfumes/alpine-nginx-nodejs:0.0.1
    ports:
        - "80"
        - "8080"
    environment:
       - VIRTUAL_HOST=webproject.dev
    volumes:
        - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
        - ./containers/web/webproject.dev.conf:/etc/nginx/sites-enabled/webproject.dev.conf
        - ./dist:/srv/www/
